"""initial

Revision ID: e5ffaf9e0e5e
Revises: 
Create Date: 2026-03-11 17:12:24.064895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5ffaf9e0e5e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allergies_indicators',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('canonical_name', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('target_level_min', sa.Float(), nullable=True),
    sa.Column('target_level_max', sa.Float(), nullable=True),
    sa.Column('target_reached', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allergies_indicators_patient_id'), 'allergies_indicators', ['patient_id'], unique=False)
    op.create_table('analyzes_docs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyzes_docs_patient_id'), 'analyzes_docs', ['patient_id'], unique=False)
    op.create_table('diseases_history_docs',
    sa.Column('icd_code', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diseases_history_docs_patient_id'), 'diseases_history_docs', ['patient_id'], unique=False)
    op.create_table('family_history_indicators',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('canonical_name', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('target_level_min', sa.Float(), nullable=True),
    sa.Column('target_level_max', sa.Float(), nullable=True),
    sa.Column('target_reached', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_history_indicators_patient_id'), 'family_history_indicators', ['patient_id'], unique=False)
    op.create_table('general_indicators',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('canonical_name', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('target_level_min', sa.Float(), nullable=True),
    sa.Column('target_level_max', sa.Float(), nullable=True),
    sa.Column('target_reached', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_general_indicators_patient_id'), 'general_indicators', ['patient_id'], unique=False)
    op.create_table('laboratory_indicators',
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('canonical_name', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('target_level_min', sa.Float(), nullable=True),
    sa.Column('target_level_max', sa.Float(), nullable=True),
    sa.Column('target_reached', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_laboratory_indicators_patient_id'), 'laboratory_indicators', ['patient_id'], unique=False)
    op.create_table('lifestyle_indicators',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('canonical_name', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('target_level_min', sa.Float(), nullable=True),
    sa.Column('target_level_max', sa.Float(), nullable=True),
    sa.Column('target_reached', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lifestyle_indicators_patient_id'), 'lifestyle_indicators', ['patient_id'], unique=False)
    op.create_table('other_docs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_other_docs_patient_id'), 'other_docs', ['patient_id'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendations_docs',
    sa.Column('specialty', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_docs_patient_id'), 'recommendations_docs', ['patient_id'], unique=False)
    op.create_table('vaccinations_indicators',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('canonical_name', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('target_level_min', sa.Float(), nullable=True),
    sa.Column('target_level_max', sa.Float(), nullable=True),
    sa.Column('target_reached', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vaccinations_indicators_patient_id'), 'vaccinations_indicators', ['patient_id'], unique=False)
    op.create_table('diseases_history_doc_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('icd_code', sa.String(), nullable=False),
    sa.Column('diagnosis_date', sa.String(), nullable=False),
    sa.Column('doctor', sa.String(), nullable=False),
    sa.Column('specialty', sa.String(), nullable=False),
    sa.Column('nosology', sa.String(), nullable=False),
    sa.Column('disease_type', sa.String(), nullable=False),
    sa.Column('clinic_name', sa.String(), nullable=False),
    sa.Column('anamnesis', sa.String(), nullable=False),
    sa.Column('clinical_findings', sa.String(), nullable=True),
    sa.Column('diagnosis', sa.String(), nullable=True),
    sa.Column('treatment_plan', sa.String(), nullable=True),
    sa.Column('conclusion', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['diseases_history_docs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id'], ['diseases_history_docs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendations_doc_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('icd_code', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('doctor', sa.String(), nullable=False),
    sa.Column('specialty', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('clinic_name', sa.String(), nullable=False),
    sa.Column('instructions', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['recommendations_docs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id'], ['recommendations_docs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommendations_doc_details')
    op.drop_table('diseases_history_doc_details')
    op.drop_index(op.f('ix_vaccinations_indicators_patient_id'), table_name='vaccinations_indicators')
    op.drop_table('vaccinations_indicators')
    op.drop_index(op.f('ix_recommendations_docs_patient_id'), table_name='recommendations_docs')
    op.drop_table('recommendations_docs')
    op.drop_table('patients')
    op.drop_index(op.f('ix_other_docs_patient_id'), table_name='other_docs')
    op.drop_table('other_docs')
    op.drop_index(op.f('ix_lifestyle_indicators_patient_id'), table_name='lifestyle_indicators')
    op.drop_table('lifestyle_indicators')
    op.drop_index(op.f('ix_laboratory_indicators_patient_id'), table_name='laboratory_indicators')
    op.drop_table('laboratory_indicators')
    op.drop_index(op.f('ix_general_indicators_patient_id'), table_name='general_indicators')
    op.drop_table('general_indicators')
    op.drop_index(op.f('ix_family_history_indicators_patient_id'), table_name='family_history_indicators')
    op.drop_table('family_history_indicators')
    op.drop_index(op.f('ix_diseases_history_docs_patient_id'), table_name='diseases_history_docs')
    op.drop_table('diseases_history_docs')
    op.drop_index(op.f('ix_analyzes_docs_patient_id'), table_name='analyzes_docs')
    op.drop_table('analyzes_docs')
    op.drop_index(op.f('ix_allergies_indicators_patient_id'), table_name='allergies_indicators')
    op.drop_table('allergies_indicators')
    # ### end Alembic commands ###
